# -*- coding: utf-8 -*-
"""gpt final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9HZEgju6OLzbZpgaUe9TGgWveBXE9WK
"""

pip install faiss-cpu sentence-transformers transformers xgboost ultralytics roboflow opencv-python matplotlib seaborn pandas numpy plotly scipy scikit-learn

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import warnings
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
from collections import Counter

import cv2
import faiss
import numpy as np
import pandas as pd
import torch
import xgboost as xgb
from scipy import integrate
from sentence_transformers import SentenceTransformer
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from ultralytics import YOLO


# ============================================================================
# FOOD DENSITY MAP (g/cm^3 ~= g/mL)
# ============================================================================
FOOD_DENSITY_MAP: Dict[str, float] = {
    'aloogobi': 1.05, 'aloomasala': 1.10, 'bhatura': 0.40,
    'bhindimasala': 1.02, 'biryani': 1.95, 'chai': 1.03,
    'chole': 1.15, 'coconutchutney': 1.05, 'dal': 1.08,
    'dosa': 0.50, 'dumaloo': 1.05, 'fishcurry': 1.05,
    'ghevar': 0.35, 'greenchutney': 1.05, 'gulabjamun': 1.15,
    'idli': 0.65, 'jalebi': 0.85, 'kebab': 0.95,
    'kheer': 1.05, 'kulfi': 0.85, 'lassi': 1.02,
    'muttoncurry': 1.10, 'onionpakoda': 0.55, 'palakpaneer': 1.05,
    'poha': 1.0, 'rajmacurry': 1.15, 'samosa': 0.70,
    'rasmalai': 0.95, 'whiterice': 1.05, 'white rice': 1.05,
    'shahipaneer': 1.08, 'shahi paneer': 1.08,
    'default': 0.45,
}

# Optional fallback average item weights for discrete items.
ITEM_AVG_WEIGHT_G: Dict[str, float] = {
    'idli': 55.0,
    'rasmalai': 40.0,
    'dosa': 35.0,
    'ghevar': 35.0,
    'kulfi': 65.0,
    'jalebi': 20.0,
    'gulabjamun': 35.0,
    'onionpakoda': 15.0,
    'samosa': 100.0,
    'bhatura': 80.0,
}


# ============================================================================
# SECTION 1: FOOD CATEGORY CLASSIFIER
# ============================================================================
class FoodCategoryClassifier:
    RICE_ITEMS = {'biryani', 'white rice', 'poha', 'whiterice'}
    LIQUID_CURRIES_BOWL = {
        'shahi paneer', 'rajma curry', 'mutton curry', 'kheer', 'dum aloo',
        'aloo gobi', 'aloo masala', 'coconut chutney', 'bhindi masala',
        'fish curry', 'dal', 'shahipaneer', 'rajmacurry', 'muttoncurry',
        'dumaloo', 'aloogobi', 'aloomasala', 'coconutchutney', 'bhindimasala',
        'fishcurry', 'chole'
    }
    LIQUIDS_IN_CUP = {'lassi', 'chai'}
    ITEMS = {'idli', 'rasmalai', 'dosa', 'ghevar', 'kulfi', 'jalebi', 'gulabjamun', 'onionpakoda', 'samosa', 'bhatura'}

    @classmethod
    def classify_food(cls, food_name: str) -> Tuple[str, str]:
        food_lower = food_name.lower().strip()
        if food_lower in cls.RICE_ITEMS:
            return 'rice', 'portion_estimation'
        if food_lower in cls.LIQUID_CURRIES_BOWL:
            return 'liquid_curries_bowl', 'liquid_estimation_bowl'
        if food_lower in cls.LIQUIDS_IN_CUP:
            return 'liquids_in_cup', 'liquid_estimation_cup'
        if food_lower in cls.ITEMS:
            return 'items', 'item_counting'
        return 'other_items', 'not_implemented'


# ============================================================================
# SECTION 2: IMPROVED LIQUID VOLUME ESTIMATOR
# ============================================================================
class LiquidVolumeEstimator:
    """Improved container/cup/bowl capacity estimator.

    Main changes vs the older og_file logic:
    - uses consistent px_to_mm scaling everywhere
    - uses top view to estimate opening ratio when available
    - avoids the old partial '* 3' geometry inflation
    - reconstructs full side profile rather than sparse polynomial points
    - does not silently assume the container is always 100% full
    """

    def __init__(self, px_to_mm: float = 0.3438, debug: bool = False):
        self.px_to_mm = float(px_to_mm)
        self.debug = debug

    def preprocess(self, image: np.ndarray) -> np.ndarray:
        if image is None:
            raise ValueError("Input image is None")
        if image.ndim == 3:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        else:
            gray = image.copy()
        gray = cv2.GaussianBlur(gray, (5, 5), 0)
        gray = cv2.medianBlur(gray, 5)
        return gray

    def _largest_mask_from_binary(self, binary: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        if not contours:
            raise ValueError("No contour detected")
        contour = max(contours, key=cv2.contourArea)
        mask = np.zeros_like(binary)
        cv2.drawContours(mask, [contour], -1, 255, -1)
        return mask, contour

    def segment_container(self, image: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        gray = self.preprocess(image)
        candidates = []
        for mode in [cv2.THRESH_BINARY + cv2.THRESH_OTSU, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU]:
            _, th = cv2.threshold(gray, 0, 255, mode)
            th = cv2.morphologyEx(th, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8), iterations=2)
            th = cv2.morphologyEx(th, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=1)
            try:
                mask, contour = self._largest_mask_from_binary(th)
                area = cv2.contourArea(contour)
                candidates.append((area, mask, contour))
            except Exception:
                pass
        if not candidates:
            edges = cv2.Canny(gray, 60, 160)
            edges = cv2.dilate(edges, np.ones((3, 3), np.uint8), iterations=1)
            edges = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, np.ones((7, 7), np.uint8), iterations=2)
            return self._largest_mask_from_binary(edges)
        candidates.sort(key=lambda x: x[0], reverse=True)
        _, mask, contour = candidates[0]
        return mask, contour

    def _mask_profile(self, mask: np.ndarray) -> Dict[str, np.ndarray]:
        ys = np.where(mask > 0)[0]
        if ys.size == 0:
            raise ValueError("Empty mask")
        y_top, y_bottom = int(ys.min()), int(ys.max())

        rows, lefts, rights, widths = [], [], [], []
        for y in range(y_top, y_bottom + 1):
            xs = np.where(mask[y] > 0)[0]
            if xs.size < 3:
                continue
            rows.append(y)
            lefts.append(xs.min())
            rights.append(xs.max())
            widths.append(xs.max() - xs.min())

        rows = np.asarray(rows)
        lefts = np.asarray(lefts, dtype=float)
        rights = np.asarray(rights, dtype=float)
        widths = np.asarray(widths, dtype=float)
        centers = (lefts + rights) / 2.0
        radii = widths / 2.0

        #smoothing
        if len(radii) >= 9:
            k = 9
            kernel = np.ones(k) / k
            radii = np.convolve(radii, kernel, mode="same")
            centers = np.convolve(centers, kernel, mode="same")

        return {
            "rows": rows,
            "lefts": lefts,
            "rights": rights,
            "widths": widths,
            "centers": centers,
            "radii": radii,
            "y_top": y_top,
            "y_bottom": y_bottom,
        }

    def _robust_band_stat(self, arr: np.ndarray, frac: float, top: bool = True) -> float:
        n = max(3, int(len(arr) * frac))
        band = arr[:n] if top else arr[-n:]
        return float(np.median(band))

    def _infer_container_type(self, rim_diam_mm: float, base_diam_mm: float, height_mm: float, force: Optional[str]) -> str:
        if force is not None:
            return force
        wh = rim_diam_mm / max(height_mm, 1e-6)
        rb = rim_diam_mm / max(base_diam_mm, 1e-6)
        if wh >= 1.0 or rb >= 1.05:
            return "bowl"
        return "cup"

    def _opening_from_top_view(self, top_view_path: Optional[str]) -> Dict[str, Any]:
        if not top_view_path:
            return {
                "outer_diameter_px": None,
                "inner_diameter_px": None,
                "inner_outer_ratio": None,
                "opening_mask": None,
            }
        img = cv2.imread(top_view_path)
        if img is None:
            raise FileNotFoundError(f"Top-view image not found: {top_view_path}")

        gray = self.preprocess(img)
        circles = []
        for mode in [cv2.THRESH_BINARY + cv2.THRESH_OTSU, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU]:
            _, th = cv2.threshold(gray, 0, 255, mode)
            th = cv2.morphologyEx(th, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8), iterations=2)
            contours, _ = cv2.findContours(th, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
            for c in contours:
                area = cv2.contourArea(c)
                if area < 200:
                    continue
                perim = cv2.arcLength(c, True)
                if perim <= 0:
                    continue
                circularity = 4.0 * np.pi * area / (perim * perim)
                if circularity < 0.45:
                    continue
                (_, _), radius = cv2.minEnclosingCircle(c)
                circles.append((area, radius * 2.0, c, th))

        if not circles:
            return {
                "outer_diameter_px": None,
                "inner_diameter_px": None,
                "inner_outer_ratio": None,
                "opening_mask": None,
            }

        circles.sort(key=lambda x: x[0], reverse=True)
        outer_diam_px = float(circles[0][1])
        outer_contour = circles[0][2]
        outer_th = circles[0][3]

        inner_diam_px = None
        outer_area = cv2.contourArea(outer_contour)
        for area, diam_px, c, _ in circles[1:]:
            if area < 0.15 * outer_area:
                continue
            (cx1, cy1), _ = cv2.minEnclosingCircle(outer_contour)
            (cx2, cy2), _ = cv2.minEnclosingCircle(c)
            if np.hypot(cx1 - cx2, cy1 - cy2) <= 0.2 * (outer_diam_px / 2.0):
                inner_diam_px = float(diam_px)
                break

        ratio = None
        if inner_diam_px is not None and outer_diam_px > 0:
            ratio = float(np.clip(inner_diam_px / outer_diam_px, 0.5, 0.99))

        return {
            "outer_diameter_px": outer_diam_px,
            "inner_diameter_px": inner_diam_px,
            "inner_outer_ratio": ratio,
            "opening_mask": outer_th,
        }

    def register_container(
        self,
        frontal_image_path: str,
        top_view_path: Optional[str] = None,
        manual_wall_thickness_mm: Optional[float] = None,
        force_container_type: Optional[str] = None,
        known_height_mm: Optional[float] = None,
        known_rim_diameter_mm: Optional[float] = None,
    ) -> Tuple[str, float, Dict[str, Any]]:
        frontal = cv2.imread(frontal_image_path)
        if frontal is None:
            raise FileNotFoundError(f"Frontal image not found: {frontal_image_path}")

        mask, _ = self.segment_container(frontal)
        profile = self._mask_profile(mask)

        rows = profile["rows"]
        widths_px = profile["widths"]
        radii_px = profile["radii"]
        y_top = profile["y_top"]
        y_bottom = profile["y_bottom"]
        total_height_px = max(1.0, y_bottom - y_top)
        rim_diameter_px = self._robust_band_stat(widths_px, frac=0.06, top=True)
        base_diameter_px = self._robust_band_stat(widths_px, frac=0.06, top=False)

        px_to_mm = self.px_to_mm
        if known_height_mm is not None and total_height_px > 0:
            px_to_mm = float(known_height_mm) / float(total_height_px)
        elif known_rim_diameter_mm is not None and rim_diameter_px > 0:
            px_to_mm = float(known_rim_diameter_mm) / float(rim_diameter_px)
        else:
            warnings.warn(
                "No physical calibration was provided. Absolute volume still depends on fallback px_to_mm.",
                RuntimeWarning,
            )

        rim_diameter_mm = rim_diameter_px * px_to_mm
        base_diameter_mm = base_diameter_px * px_to_mm
        total_height_mm = total_height_px * px_to_mm
        container_type = self._infer_container_type(rim_diameter_mm, base_diameter_mm, total_height_mm, force_container_type)

        top_stats = self._opening_from_top_view(top_view_path)

        if manual_wall_thickness_mm is not None:
            wall_thickness_mm = float(manual_wall_thickness_mm)
        elif top_stats["inner_outer_ratio"] is not None:
            wall_thickness_mm = (rim_diameter_mm * (1.0 - top_stats["inner_outer_ratio"])) / 2.0
        else:
            wall_thickness_mm = 2.5 if container_type == "cup" else 1.8

        wall_thickness_mm = float(np.clip(wall_thickness_mm, 0.8, max(6.0, rim_diameter_mm * 0.12)))
        bottom_thickness_mm = wall_thickness_mm * (1.4 if container_type == "cup" else 1.1)
        usable_height_mm = max(1.0, total_height_mm - bottom_thickness_mm)

        z_mm = (rows - y_top) * px_to_mm
        outer_r_mm = radii_px * px_to_mm
        inner_r_mm = np.maximum(outer_r_mm - wall_thickness_mm, 0.0)

        cavity_z_mm = np.clip(z_mm, 0.0, usable_height_mm)
        valid = (cavity_z_mm >= 0.0) & (cavity_z_mm <= usable_height_mm) & (inner_r_mm >= 0.0)
        cavity_z_mm = cavity_z_mm[valid]
        inner_r_mm = inner_r_mm[valid]

        order = np.argsort(cavity_z_mm)
        cavity_z_mm = cavity_z_mm[order]
        inner_r_mm = inner_r_mm[order]

        uniq_z = np.unique(cavity_z_mm)
        avg_r = [float(np.mean(inner_r_mm[np.isclose(cavity_z_mm, z)])) for z in uniq_z]
        cavity_z_mm = uniq_z
        inner_r_mm = np.asarray(avg_r, dtype=float)

        if cavity_z_mm.size < 5:
            cavity_z_mm = np.linspace(0.0, usable_height_mm, 100)
            inner_base_r = max(base_diameter_mm / 2.0 - wall_thickness_mm, 0.1)
            inner_rim_r = max(rim_diameter_mm / 2.0 - wall_thickness_mm, 0.1)
            inner_r_mm = np.linspace(inner_base_r, inner_rim_r, cavity_z_mm.size)
        else:
            dense_z = np.linspace(0.0, usable_height_mm, 300)
            dense_r = np.interp(dense_z, cavity_z_mm, inner_r_mm)
            cavity_z_mm = dense_z
            inner_r_mm = np.maximum(dense_r, 0.0)

        if top_stats["inner_outer_ratio"] is not None:
            target_rim_inner_mm = (rim_diameter_mm * top_stats["inner_outer_ratio"]) / 2.0
            current_rim = max(inner_r_mm[-1], 1e-6)
            scale = target_rim_inner_mm / current_rim
            if 0.7 <= scale <= 1.2:
                inner_r_mm *= scale
            else:
                inner_r_mm[-20:] = np.linspace(inner_r_mm[-20], target_rim_inner_mm, 20)

        capacity_ml = float(integrate.trapezoid(np.pi * (inner_r_mm ** 2), cavity_z_mm) / 1000.0)

        def r_inner(z_val: float) -> float:
            z_val = float(np.clip(z_val, 0.0, usable_height_mm))
            return float(np.interp(z_val, cavity_z_mm, inner_r_mm))

        container_data = {
            "container_type": container_type,
            "rim_diameter_mm": rim_diameter_mm,
            "base_diameter_mm": base_diameter_mm,
            "total_height_mm": total_height_mm,
            "effective_height_mm": usable_height_mm,
            "wall_thickness_mm": wall_thickness_mm,
            "bottom_thickness_mm": bottom_thickness_mm,
            "inner_rim_diameter_mm": 2.0 * inner_r_mm[-1],
            "capacity_ml": capacity_ml,
            "r_inner_function": r_inner,
            "z_samples_mm": cavity_z_mm,
            "r_samples_mm": inner_r_mm,
            "top_view_inner_outer_ratio": top_stats["inner_outer_ratio"],
            "px_to_mm_used": px_to_mm,
        }
        return container_type, capacity_ml, container_data

    def estimate_liquid_volume(self, container_data: Dict[str, Any], liquid_top_view_path: str) -> Dict[str, float]:
        img = cv2.imread(liquid_top_view_path)
        if img is None:
            raise FileNotFoundError(f"Liquid top-view image not found: {liquid_top_view_path}")

        gray = self.preprocess(img)
        candidates = []
        for mode in [cv2.THRESH_BINARY + cv2.THRESH_OTSU, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU]:
            _, th = cv2.threshold(gray, 0, 255, mode)
            th = cv2.morphologyEx(th, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=1)
            th = cv2.morphologyEx(th, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8), iterations=2)
            contours, _ = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
            for c in contours:
                area = cv2.contourArea(c)
                if area < 100:
                    continue
                perim = cv2.arcLength(c, True)
                if perim <= 0:
                    continue
                circularity = 4.0 * np.pi * area / (perim * perim)
                if circularity < 0.4:
                    continue
                (_, _), radius = cv2.minEnclosingCircle(c)
                candidates.append((area, radius))

        if not candidates:
            raise ValueError("No liquid surface detected in top view")

        candidates.sort(key=lambda x: x[0], reverse=True)
        liquid_radius_px = float(candidates[0][1])
        px_to_mm = float(container_data.get("px_to_mm_used", self.px_to_mm))
        liquid_radius_mm = liquid_radius_px * px_to_mm

        z_samples = np.asarray(container_data["z_samples_mm"], dtype=float)
        r_samples = np.asarray(container_data["r_samples_mm"], dtype=float)
        capacity_ml = float(container_data["capacity_ml"])

        idx = int(np.argmin(np.abs(r_samples - liquid_radius_mm)))
        fill_height_mm = float(z_samples[idx])
        fill_volume_ml = float(integrate.trapezoid(np.pi * (r_samples[: idx + 1] ** 2), z_samples[: idx + 1]) / 1000.0)
        fill_pct = 100.0 * fill_volume_ml / max(capacity_ml, 1e-6)

        return {
            "container_type": container_data["container_type"],
            "curry_volume_ml": fill_volume_ml,
            "fill_height_mm": fill_height_mm,
            "fill_percentage": fill_pct,
            "surface_radius_mm": liquid_radius_mm,
            "container_capacity_ml": capacity_ml,
        }


# ============================================================================
# SECTION 3: PORTION ESTIMATOR (MiDaS)
# ============================================================================
class PortionEstimator:
    def __init__(self, device: Optional[torch.device] = None):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu") if device is None else device
        self.midas = None
        self.midas_transform = None
        self.model_loaded = False
        self.last_depth_map = None
        self.last_mask = None
        self.last_image = None

    def load_midas_model(self, model_type: str = "DPT_Hybrid") -> bool:
        self.midas = torch.hub.load("intel-isl/MiDaS", model_type)
        self.midas.to(self.device)
        self.midas.eval()
        midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
        self.midas_transform = midas_transforms.dpt_transform
        self.model_loaded = True
        return self.model_loaded

    def generate_depth_map(self, image_path: str) -> Tuple[np.ndarray, np.ndarray]:
        if not self.model_loaded:
            raise RuntimeError("MiDaS model not loaded")
        img = cv2.imread(image_path)
        if img is None:
            raise FileNotFoundError(f"Image not found: {image_path}")
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.last_image = img_rgb
        input_batch = self.midas_transform(img_rgb).to(self.device)
        with torch.no_grad():
            prediction = self.midas(input_batch)
        depth_map = prediction.squeeze().cpu().numpy()
        depth_map = cv2.resize(depth_map, (img.shape[1], img.shape[0]))
        self.last_depth_map = depth_map
        return depth_map, img_rgb

    def create_food_mask(
        self,
        depth_map: Optional[np.ndarray] = None,
        auto_mask: bool = True,
        x1: Optional[int] = None,
        y1: Optional[int] = None,
        x2: Optional[int] = None,
        y2: Optional[int] = None,
        h_ratio: float = 0.20,
        w_ratio: float = 0.80,
    ) -> np.ndarray:
        if depth_map is None:
            depth_map = self.last_depth_map
        h, w = depth_map.shape
        if auto_mask:
            mask = np.zeros((h, w), dtype=np.uint8)
            mask[int(h * h_ratio):int(h * w_ratio), int(w * h_ratio):int(w * w_ratio)] = 1
        else:
            if None in (x1, y1, x2, y2):
                raise ValueError("Manual coordinates required when auto_mask=False")
            mask = np.zeros(depth_map.shape, dtype=np.uint8)
            mask[y1:y2, x1:x2] = 1
        self.last_mask = mask
        return mask

    def calculate_portion_metrics(
        self,
        depth_map: Optional[np.ndarray] = None,
        mask: Optional[np.ndarray] = None,
        plate_real_diameter_cm: float = 25,
        plate_pixel_diameter: float = 520,
        max_food_height_cm: float = 2.0,
        density: float = 0.45,
    ) -> Dict[str, float]:
        if depth_map is None:
            depth_map = self.last_depth_map
        if mask is None:
            mask = self.last_mask
        scale_cm_per_pixel = plate_real_diameter_cm / plate_pixel_diameter
        depth_norm = (depth_map - depth_map.min()) / (depth_map.max() - depth_map.min() + 1e-8)
        food_depth = np.mean(depth_norm[mask == 1])
        plate_depth = np.mean(depth_norm)
        relative_thickness = abs(plate_depth - food_depth)
        thickness_cm = relative_thickness * max_food_height_cm
        pixel_area = np.sum(mask)
        area_cm2 = pixel_area * (scale_cm_per_pixel ** 2)
        volume_cm3 = area_cm2 * thickness_cm
        weight_g = volume_cm3 * density
        return {
            'scale_cm_per_pixel': float(scale_cm_per_pixel),
            'relative_thickness': float(relative_thickness),
            'thickness_cm': float(thickness_cm),
            'area_cm2': float(area_cm2),
            'volume_cm3': float(volume_cm3),
            'weight_g': float(weight_g),
        }


# ============================================================================
# SECTION 4: INTEGRATED FOOD ESTIMATION SYSTEM
# ============================================================================
class IntegratedFoodEstimator:
    def __init__(self, yolo_model_path: str, px_to_mm: float = 0.3438):
        self.yolo_model = YOLO(yolo_model_path)
        self.classifier = FoodCategoryClassifier()
        self.liquid_estimator = LiquidVolumeEstimator(px_to_mm=px_to_mm)
        self.portion_estimator = PortionEstimator()
        self.last_prediction: Optional[Dict[str, Any]] = None

    def predict(self, image_path: str, conf_threshold: float = 0.25) -> Dict[str, Any]:
        if not os.path.exists(image_path):
            raise FileNotFoundError(f"Image not found: {image_path}")
        results = self.yolo_model.predict(source=image_path, conf=conf_threshold, iou=0.45, save=False)
        predictions: List[Dict[str, Any]] = []
        for r in results:
            if hasattr(r, 'boxes') and r.boxes is not None:
                for box in r.boxes:
                    class_id = int(box.cls[0])
                    confidence = float(box.conf[0])
                    class_name = self.yolo_model.names[class_id]
                    predictions.append({
                        'class_id': class_id,
                        'class_name': class_name,
                        'confidence': confidence,
                    })
        if not predictions:
            raise ValueError("No food items detected in the image")

        class_counts = Counter(pred['class_name'] for pred in predictions)
        top_prediction = max(predictions, key=lambda x: x['confidence'])
        top_category, top_method = self.classifier.classify_food(top_prediction['class_name'])
        self.last_prediction = {
            'class_name': top_prediction['class_name'],
            'class_id': top_prediction['class_id'],
            'confidence': top_prediction['confidence'],
            'category': top_category,
            'estimation_method': top_method,
            'all_detections': predictions,
            'class_counts': dict(class_counts),
            'total_items': len(predictions),
        }
        return self.last_prediction

    def estimate(
        self,
        image_path: str,
        container_frontal_path: Optional[str] = None,
        container_top_view_path: Optional[str] = None,
        liquid_surface_top_view_path: Optional[str] = None,
        auto_mask: bool = True,
        predicted_class: Optional[str] = None,
        known_height_mm: Optional[float] = None,
        known_rim_diameter_mm: Optional[float] = None,
    ) -> Dict[str, Any]:
        if predicted_class is None:
            if self.last_prediction is None:
                raise ValueError("No prediction available. Call predict() first or provide predicted_class.")
            predicted_class = self.last_prediction['class_name']
            class_counts = self.last_prediction.get('class_counts', {})
        else:
            class_counts = self.last_prediction.get('class_counts', {predicted_class: 1}) if self.last_prediction else {predicted_class: 1}

        category, method = self.classifier.classify_food(predicted_class)

        if method == 'portion_estimation':
            return self._estimate_rice(predicted_class, image_path, auto_mask)
        if method == 'liquid_estimation_bowl':
            if container_frontal_path is None:
                raise ValueError("Container frontal image required for liquid estimation")
            return self._estimate_liquid(
                predicted_class, 'bowl', container_frontal_path, container_top_view_path,
                liquid_surface_top_view_path, known_height_mm, known_rim_diameter_mm,
            )
        if method == 'liquid_estimation_cup':
            if container_frontal_path is None:
                raise ValueError("Container frontal image required for liquid estimation")
            return self._estimate_liquid(
                predicted_class, 'cup', container_frontal_path, container_top_view_path,
                liquid_surface_top_view_path, known_height_mm, known_rim_diameter_mm,
            )
        if method == 'item_counting':
            return self._estimate_items(predicted_class, class_counts)
        return {'status': 'not_implemented', 'predicted_class': predicted_class, 'category': category}

    def _estimate_rice(self, food_name: str, image_path: str, auto_mask: bool) -> Dict[str, Any]:
        density = FOOD_DENSITY_MAP.get(food_name.lower().strip(), FOOD_DENSITY_MAP['default'])
        if not self.portion_estimator.model_loaded:
            self.portion_estimator.load_midas_model(model_type="DPT_Hybrid")
        depth_map, img_rgb = self.portion_estimator.generate_depth_map(image_path)
        mask = self.portion_estimator.create_food_mask(depth_map=depth_map, auto_mask=auto_mask)
        metrics = self.portion_estimator.calculate_portion_metrics(
            depth_map=depth_map,
            mask=mask,
            plate_real_diameter_cm=25,
            plate_pixel_diameter=520,
            max_food_height_cm=2.0,
            density=density,
        )
        return {
            'status': 'success',
            'predicted_class': food_name,
            'method': 'portion_estimation',
            'results': metrics,
        }

    def _estimate_liquid(
        self,
        food_name: str,
        container_type_hint: str,
        frontal_path: str,
        top_view_path: Optional[str],
        liquid_surface_top_view_path: Optional[str],
        known_height_mm: Optional[float],
        known_rim_diameter_mm: Optional[float],
    ) -> Dict[str, Any]:
        container_type, capacity_ml, container_data = self.liquid_estimator.register_container(
            frontal_image_path=frontal_path,
            top_view_path=top_view_path,
            force_container_type=container_type_hint,
            known_height_mm=known_height_mm,
            known_rim_diameter_mm=known_rim_diameter_mm,
        )

        if liquid_surface_top_view_path is not None:
            liquid_stats = self.liquid_estimator.estimate_liquid_volume(container_data, liquid_surface_top_view_path)
            estimated_volume_ml = liquid_stats['curry_volume_ml']
            fill_height_mm = liquid_stats['fill_height_mm']
            fill_percentage = liquid_stats['fill_percentage']
            surface_radius_mm = liquid_stats['surface_radius_mm']
            note = 'Fill-volume estimated from separate liquid-surface top view.'
        else:
            estimated_volume_ml = capacity_ml
            fill_height_mm = None
            fill_percentage = None
            surface_radius_mm = None
            note = 'Capacity only. Provide liquid_surface_top_view_path to estimate actual fill-volume.'

        return {
            'status': 'success',
            'predicted_class': food_name,
            'method': f'liquid_estimation_{container_type_hint}',
            'results': {
                'container_type': container_type,
                'estimated_volume_ml': float(estimated_volume_ml),
                'curry_volume_ml': float(estimated_volume_ml),
                'container_capacity_ml': float(capacity_ml),
                'fill_height_mm': fill_height_mm,
                'fill_percentage': fill_percentage,
                'surface_radius_mm': surface_radius_mm,
                'geometry_debug': {
                    'rim_diameter_mm': container_data['rim_diameter_mm'],
                    'base_diameter_mm': container_data['base_diameter_mm'],
                    'effective_height_mm': container_data['effective_height_mm'],
                    'wall_thickness_mm': container_data['wall_thickness_mm'],
                    'px_to_mm_used': container_data['px_to_mm_used'],
                },
                'note': note,
            },
        }

    def _estimate_items(self, food_name: str, class_counts: Dict[str, int]) -> Dict[str, Any]:
        items_in_category: Dict[str, int] = {}
        total_count = 0
        estimated_weight_g = 0.0
        for item_name, count in class_counts.items():
            category, _ = self.classifier.classify_food(item_name)
            if category == 'items':
                items_in_category[item_name] = count
                total_count += count
                estimated_weight_g += ITEM_AVG_WEIGHT_G.get(item_name.lower().strip(), 0.0) * count
        return {
            'status': 'success',
            'predicted_class': food_name,
            'method': 'item_counting',
            'results': {
                'total_items': total_count,
                'item_counts': items_in_category,
                'all_detections': class_counts,
                'estimated_weight_g': estimated_weight_g,
            },
        }

    def predict_and_estimate(
        self,
        image_path: str,
        container_frontal_path: Optional[str] = None,
        container_top_view_path: Optional[str] = None,
        liquid_surface_top_view_path: Optional[str] = None,
        auto_mask: bool = True,
        known_height_mm: Optional[float] = None,
        known_rim_diameter_mm: Optional[float] = None,
    ) -> Dict[str, Any]:
        prediction = self.predict(image_path)
        estimation = self.estimate(
            image_path=image_path,
            container_frontal_path=container_frontal_path,
            container_top_view_path=container_top_view_path,
            liquid_surface_top_view_path=liquid_surface_top_view_path,
            auto_mask=auto_mask,
            known_height_mm=known_height_mm,
            known_rim_diameter_mm=known_rim_diameter_mm,
        )
        return {'prediction': prediction, 'estimation': estimation}


# ============================================================================
# SECTION 5: NUTRITION RAG + XGBOOST FALLBACK
# ============================================================================
@dataclass
class NutritionConfig:
    indb_file_path: str = "INDB.xlsx"
    embedding_model_name: str = "all-MiniLM-L6-v2"
    llm_model_name: str = "Qwen/Qwen2.5-3B-Instruct"
    top_k_retrieval: int = 5
    similarity_threshold: float = 0.75
    random_state: int = 42
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    column_mapping: Optional[Dict[str, str]] = None

    def __post_init__(self) -> None:
        if self.column_mapping is None:
            self.column_mapping = {
                "food_name": "food_name",
                "calories": "energy_kc",
                "protein": "protein_g",
                "carbs": "carb_g",
                "fats": "fat_g",
            }


class DataProcessor:
    def __init__(self, file_path: str, column_mapping: Dict[str, str]):
        self.file_path = file_path
        self.column_mapping = column_mapping
        self.df: Optional[pd.DataFrame] = None
        self.processed_df: Optional[pd.DataFrame] = None

    def load_data(self) -> pd.DataFrame:
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"{self.file_path} not found")
        self.df = pd.read_excel(self.file_path)
        return self.df

    def preprocess(self) -> pd.DataFrame:
        if self.df is None:
            raise ValueError("Data not loaded. Call load_data() first.")

        mapped_cols: Dict[str, str] = {}
        for logical_name, excel_header in self.column_mapping.items():
            logical_name = logical_name.strip()
            excel_header = excel_header.strip()
            if excel_header not in self.df.columns:
                found = False
                for col in self.df.columns:
                    if excel_header.split()[0].lower() in col.lower():
                        mapped_cols[logical_name] = col
                        found = True
                        break
                if not found:
                    raise ValueError(f"Column '{excel_header}' not found in dataset. Update column_mapping.")
            else:
                mapped_cols[logical_name] = excel_header

        self.processed_df = self.df[list(mapped_cols.values())].copy()
        self.processed_df.columns = list(mapped_cols.keys())
        self.processed_df['food_name_clean'] = self.processed_df['food_name'].apply(self._normalize_text)

        nutrient_cols = ['calories', 'protein', 'carbs', 'fats']
        self.processed_df = self.processed_df.dropna(subset=nutrient_cols)
        for col in nutrient_cols:
            self.processed_df[col] = pd.to_numeric(self.processed_df[col], errors='coerce')
        self.processed_df = self.processed_df.dropna(subset=nutrient_cols)
        return self.processed_df

    @staticmethod
    def _normalize_text(text: str) -> str:
        if not isinstance(text, str):
            return ""
        text = text.lower()
        text = re.sub(r'[^\w\s]', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text


class EmbeddingEngine:
    def __init__(self, model_name: str, device: str):
        self.model = SentenceTransformer(model_name, device=device)
        self.dimension = self.model.get_sentence_embedding_dimension()

    def encode(self, texts: List[str]) -> np.ndarray:
        embeddings = self.model.encode(texts, convert_to_numpy=True, normalize_embeddings=True)
        return embeddings.astype('float32')


class VectorStore:
    def __init__(self, dimension: int):
        self.index = faiss.IndexFlatIP(dimension)
        self.metadata: List[Dict[str, Any]] = []

    def add(self, embeddings: np.ndarray, metadata: List[Dict[str, Any]]) -> None:
        if len(embeddings) != len(metadata):
            raise ValueError("Embeddings and metadata length mismatch")
        self.index.add(embeddings)
        self.metadata.extend(metadata)

    def search(self, query_embedding: np.ndarray, top_k: int) -> Tuple[List[Dict[str, Any]], List[float]]:
        distances, indices = self.index.search(query_embedding, top_k)
        results, scores = [], []
        for i, idx in enumerate(indices[0]):
            if idx == -1:
                continue
            results.append(self.metadata[idx])
            scores.append(float(distances[0][i]))
        return results, scores


class XGBoostPredictor:
    def __init__(self, nutrient_cols: List[str], config: NutritionConfig):
        self.nutrient_cols = nutrient_cols
        self.config = config
        self.models: Dict[str, xgb.XGBRegressor] = {}
        self.is_trained = False

    def train(self, embeddings: np.ndarray, df: pd.DataFrame) -> None:
        X = embeddings
        y = df[self.nutrient_cols].values
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=self.config.random_state
        )
        for i, col in enumerate(self.nutrient_cols):
            model = xgb.XGBRegressor(
                objective='reg:squarederror',
                n_estimators=300,
                max_depth=6,
                learning_rate=0.08,
                random_state=self.config.random_state,
                device=self.config.device,
            )
            model.fit(X_train, y_train[:, i])
            self.models[col] = model
            _ = np.sqrt(mean_squared_error(y_test[:, i], model.predict(X_test)))
        self.is_trained = True

    def predict(self, embedding: np.ndarray) -> Dict[str, float]:
        if not self.is_trained:
            raise RuntimeError("XGBoost models not trained yet")
        if embedding.ndim == 1:
            embedding = embedding.reshape(1, -1)
        return {col: max(0.0, float(model.predict(embedding)[0])) for col, model in self.models.items()}


class LLMEngine:
    def __init__(self, model_name: str, device: str):
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map="auto" if device == "cuda" else None,
            trust_remote_code=True,
            torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        )
        self.pipe = pipeline(
            "text-generation",
            model=self.model,
            tokenizer=self.tokenizer,
            max_new_tokens=256,
            do_sample=False,
            temperature=0.0,
        )

    def generate(self, prompt: str) -> str:
        messages = [
            {"role": "system", "content": "You are a precise Nutrition Assistant. Output only the requested structured fields."},
            {"role": "user", "content": prompt},
        ]
        response = self.pipe(messages)
        return response[0]['generated_text'][-1]['content']


class NutritionRAGSystem:
    def __init__(self, config: NutritionConfig, load_llm: bool = False):
        self.config = config
        self.data_processor = DataProcessor(self.config.indb_file_path, self.config.column_mapping)
        self.embedding_engine: Optional[EmbeddingEngine] = None
        self.vector_store: Optional[VectorStore] = None
        self.xgb_predictor: Optional[XGBoostPredictor] = None
        self.llm_engine: Optional[LLMEngine] = None
        self.is_ready = False
        self.load_llm = load_llm

    def initialize(self) -> None:
        self.data_processor.load_data()
        df = self.data_processor.preprocess()
        self.embedding_engine = EmbeddingEngine(self.config.embedding_model_name, self.config.device)
        self.vector_store = VectorStore(self.embedding_engine.dimension)
        food_names = df['food_name_clean'].tolist()
        embeddings = self.embedding_engine.encode(food_names)
        self.vector_store.add(embeddings, df.to_dict('records'))
        self.xgb_predictor = XGBoostPredictor(['calories', 'protein', 'carbs', 'fats'], self.config)
        self.xgb_predictor.train(embeddings, df)
        if self.load_llm:
            self.llm_engine = LLMEngine(self.config.llm_model_name, self.config.device)
        self.is_ready = True

    def get_nutrient_data(self, food_name: str) -> Dict[str, Any]:
        if not self.is_ready:
            raise RuntimeError("NutritionRAGSystem is not initialized")
        assert self.embedding_engine is not None and self.vector_store is not None and self.xgb_predictor is not None
        query_embedding = self.embedding_engine.encode([DataProcessor._normalize_text(food_name)])
        retrieved_docs, similarity_scores = self.vector_store.search(query_embedding, self.config.top_k_retrieval)
        if retrieved_docs and similarity_scores[0] >= self.config.similarity_threshold:
            best = dict(retrieved_docs[0])
            best['source'] = 'Indian Nutrient Databank'
            best['match_similarity'] = float(similarity_scores[0])
            best['route'] = 'rag'
            return best
        predicted_vals = self.xgb_predictor.predict(query_embedding)
        predicted_vals['source'] = 'Estimated using ML model (XGBoost)'
        predicted_vals['match_similarity'] = float(similarity_scores[0]) if similarity_scores else 0.0
        predicted_vals['route'] = 'xgboost_fallback'
        return predicted_vals

    def query(self, food_name: str) -> Dict[str, Any]:
        return self.get_nutrient_data(food_name)


# ============================================================================
# SECTION 6: MERGED NUTRITION + VOLUME SYSTEM
# ============================================================================
class IntegratedNutritionVolumeSystem:
    """Merged pipeline requested by the user.

    Flow:
    YOLO prediction -> improved volume/weight estimation -> RAG/XGBoost nutrient lookup
    -> serving-level calories/protein/carbs/fats from estimated amount.
    """

    def __init__(
        self,
        yolo_model_path: str,
        indb_file_path: str,
        column_mapping: Dict[str, str],
        px_to_mm: float = 0.3438,
        similarity_threshold: float = 0.75,
        load_llm: bool = False,
    ):
        self.volume_estimator = IntegratedFoodEstimator(yolo_model_path=yolo_model_path, px_to_mm=px_to_mm)
        self.nutrition_system = NutritionRAGSystem(
            NutritionConfig(
                indb_file_path=indb_file_path,
                similarity_threshold=similarity_threshold,
                column_mapping=column_mapping,
            ),
            load_llm=load_llm,
        )
        self.nutrition_system.initialize()

    @staticmethod
    def _food_density(food_name: str) -> float:
        return FOOD_DENSITY_MAP.get(food_name.lower().strip(), FOOD_DENSITY_MAP['default'])

    def _estimate_serving_mass_g(self, food_name: str, method: str, est: Dict[str, Any]) -> Tuple[float, Dict[str, Any]]:
        results = est['results']
        meta: Dict[str, Any] = {}

        if method == 'portion_estimation':
            mass_g = float(results.get('weight_g', 0.0))
            meta['mass_source'] = 'direct_weight_from_depth_volume'
            return mass_g, meta

        if method in ['liquid_estimation_bowl', 'liquid_estimation_cup']:
            volume_ml = float(results.get('curry_volume_ml', results.get('estimated_volume_ml', 0.0)))
            density = self._food_density(food_name)
            mass_g = volume_ml * density
            meta['volume_ml'] = volume_ml
            meta['density_g_per_ml'] = density
            meta['mass_source'] = 'volume_times_density'
            return mass_g, meta

        if method == 'item_counting':
            mass_g = float(results.get('estimated_weight_g', 0.0))
            meta['mass_source'] = 'item_count_times_avg_item_weight'
            if mass_g == 0.0:
                meta['warning'] = 'No fallback average item weight available for this class.'
            return mass_g, meta

        meta['mass_source'] = 'unavailable'
        return 0.0, meta

    @staticmethod
    def _scale_per_100g(nutrient_data: Dict[str, Any], serving_mass_g: float) -> Dict[str, float]:
        factor = serving_mass_g / 100.0
        return {
            'serving_mass_g': float(serving_mass_g),
            'calories_kcal': float(nutrient_data.get('calories', 0.0)) * factor,
            'protein_g': float(nutrient_data.get('protein', 0.0)) * factor,
            'carbs_g': float(nutrient_data.get('carbs', 0.0)) * factor,
            'fats_g': float(nutrient_data.get('fats', 0.0)) * factor,
        }

    def process_image(
        self,
        image_path: str,
        container_frontal_path: Optional[str] = None,
        container_top_view_path: Optional[str] = None,
        liquid_surface_top_view_path: Optional[str] = None,
        auto_mask: bool = True,
        known_height_mm: Optional[float] = None,
        known_rim_diameter_mm: Optional[float] = None,
        conf_threshold: float = 0.25,
    ) -> Dict[str, Any]:
        prediction = self.volume_estimator.predict(image_path=image_path, conf_threshold=conf_threshold)
        estimation = self.volume_estimator.estimate(
            image_path=image_path,
            container_frontal_path=container_frontal_path,
            container_top_view_path=container_top_view_path,
            liquid_surface_top_view_path=liquid_surface_top_view_path,
            auto_mask=auto_mask,
            known_height_mm=known_height_mm,
            known_rim_diameter_mm=known_rim_diameter_mm,
        )

        food_name = prediction['class_name']
        method = prediction['estimation_method']
        nutrient_data = self.nutrition_system.get_nutrient_data(food_name)
        serving_mass_g, mass_meta = self._estimate_serving_mass_g(food_name, method, estimation)
        serving_macros = self._scale_per_100g(nutrient_data, serving_mass_g)

        result = {
            'food_name': food_name,
            'prediction': prediction,
            'estimation': estimation,
            'nutrition_lookup': {
                'route': nutrient_data.get('route'),
                'source': nutrient_data.get('source'),
                'match_similarity': nutrient_data.get('match_similarity'),
                'per_100g': {
                    'calories_kcal': float(nutrient_data.get('calories', 0.0)),
                    'protein_g': float(nutrient_data.get('protein', 0.0)),
                    'carbs_g': float(nutrient_data.get('carbs', 0.0)),
                    'fats_g': float(nutrient_data.get('fats', 0.0)),
                },
            },
            'serving_estimate': {
                **serving_macros,
                **mass_meta,
            },
        }

        return result

def print_vertical_result(result):
    print("\n" + "="*60)
    print("FINAL RESULT (VERTICAL FORMAT)")
    print("="*60)

    print(f"\nFood Name: {result['food_name']}")

    # ---------------- Prediction ----------------
    pred = result['prediction']
    print("\n--- Prediction ---")
    print(f"Class        : {pred['class_name']}")
    print(f"Confidence   : {pred['confidence']:.2%}")
    print(f"Category     : {pred['category']}")
    print(f"Method       : {pred['estimation_method']}")

    # ---------------- Volume / Estimation ----------------
    est = result['estimation']['results']
    print("\n--- Volume Estimation ---")
    for key, value in est.items():
        if key != "geometry_debug":
            print(f"{key:25}: {value}")

    # ---------------- Nutrition ----------------
    nut = result['nutrition_lookup']
    print("\n--- Nutrition (per 100g) ---")
    for k, v in nut['per_100g'].items():
        print(f"{k:20}: {v:.2f}")

    # ---------------- Serving ----------------
    serv = result['serving_estimate']
    print("\n--- Serving Nutrition ---")
    print(f"Serving Mass (g) : {serv['serving_mass_g']:.2f}")
    print(f"Calories (kcal)  : {serv['calories_kcal']:.2f}")
    print(f"Protein (g)      : {serv['protein_g']:.2f}")
    print(f"Carbs (g)        : {serv['carbs_g']:.2f}")
    print(f"Fats (g)         : {serv['fats_g']:.2f}")

    print("\n" + "="*60)

if __name__ == "__main__":
    # Example usage
    COLUMN_MAPPING = {
        "food_name": "food_name",
        "calories": "energy_kc",
        "protein": "protein_g",
        "carbs": "carb_g",
        "fats": "fat_g",
    }

    system = IntegratedNutritionVolumeSystem(
        yolo_model_path="/content/drive/MyDrive/indian_food_best.pt",
        indb_file_path="INDB.xlsx",
        column_mapping=COLUMN_MAPPING,
        px_to_mm=0.3438,
    )

    result = system.process_image(
        image_path="image.png",
        container_frontal_path='bowl_frontal.png',
        container_top_view_path='bowl_top.png',
        liquid_surface_top_view_path='image.png',
        auto_mask=True,
    )
    print_vertical_result(result)

